### ISSUE TITLE
downcase issues in the parser

### ISSUE THREAD

**Issue by failshell** [lightspeedretail/castor#10]
``` text
/opt/castor/1.0.2/lib/castor/parser.rb:57:in `block in general': undefined method `downcase' for nil:NilClass (NoMethodError)
        from /opt/castor/1.0.2/lib/castor/parser.rb:39:in `each'
        from /opt/castor/1.0.2/lib/castor/parser.rb:39:in `general'
        from /opt/castor/1.0.2/lib/castor/core.rb:93:in `processing'
        from /opt/castor/1.0.2/lib/castor/core.rb:53:in `run'
        from /usr/bin/castor:4:in `<main>'
```

**Comment by failshell** [comment]
Resolved in version 2.
