### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by senreese** [lightspeedretail/castor#12]
Possibly version related. I have been unable to get your code to execute against a test RDS.

I know my IAM role is correct, as I can test with the command line tools:
`aws rds download-db-log-file-portion --db-instance-identifier testdb  --log-file-name general/mysql-general.log.22 --max-items 1000 --output text`

However executing your tool seems to have an authentication issue, with or without the temporary credentials, I always get this error.

./castor -n testdb -r us-west-2 -t general -a -p rdsadmrole

```
/home/testguy/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.2.35/lib/aws-sdk-core/signers/v4.rb:233:in `digest': no implicit conversion of true into String (TypeError)
        from /home/testguy/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.2.35/lib/aws-sdk-core/signers/v4.rb:233:in `hmac'
        from /home/testguy/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.2.35/lib/aws-sdk-core/signers/v4.rb:117:in `signature'
        from /home/testguy/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.2.35/lib/aws-sdk-core/signers/v4.rb:106:in `authorization'
        from /home/testguy/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.2.35/lib/aws-sdk-core/signers/v4.rb:58:in `sign'
        from /home/testguy/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.2.35/lib/aws-sdk-core/signers/v4.rb:33:in `sign'
        from /home/testguy/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.2.35/lib/aws-sdk-core/plugins/request_signer.rb:93:in `sign_authenticated_requests'
        from /home/testguy/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.2.35/lib/aws-sdk-core/plugins/request_signer.rb:83:in `call'
        from /home/testguy/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.2.35/lib/aws-sdk-core/plugins/retry_errors.rb:87:in `call'
        from /home/testguy/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.2.35/lib/aws-sdk-core/query/handler.rb:27:in `call'
        from /home/testguy/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.2.35/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
        from /home/testguy/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.2.35/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
        from /home/testguy/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.2.35/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
        from /home/testguy/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.2.35/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
        from /home/testguy/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.2.35/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
        from /home/testguy/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.2.35/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
        from /home/testguy/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.2.35/lib/seahorse/client/plugins/response_target.rb:21:in `call'
        from /home/testguy/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.2.35/lib/seahorse/client/request.rb:70:in `send_request'
        from /home/testguy/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.2.35/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
        from /home/testguy/castor/lib/castor/fetcher.rb:16:in `file_size'
        from /home/testguy/castor/lib/castor/core.rb:31:in `run'
        from ./castor:4:in `<main>'

```

**Comment by failshell** [comment]
Keep an eye out for version 2 coming out soon. It will resolve a lot of weird bugs.
