### ISSUE TITLE
Trap and handle fetcher errors properly

### ISSUE THREAD

**Issue by failshell** [lightspeedretail/castor#7]
``` text
/opt/castor/1.0.2/lib/castor/fetcher.rb:17:in `file_size': undefined method `[]' for nil:NilClass (NoMethodError)
        from /opt/castor/1.0.2/lib/castor/core.rb:31:in `run'
        from /usr/bin/castor:4:in `<main>'
```

**Comment by failshell** [comment]
``` text
/opt/castor/1.0.2/lib/castor/fetcher.rb:44:in `previous_log_file': undefined method `[]' for nil:NilClass (NoMethodError)
        from /opt/castor/1.0.2/lib/castor/core.rb:81:in `processing'
        from /opt/castor/1.0.2/lib/castor/core.rb:44:in `run'
        from /usr/bin/castor:4:in `<main>'
```
