### ISSUE TITLE
Handle the existance of a lock properly

### ISSUE THREAD

**Issue by failshell** [lightspeedretail/castor#9]
``` text
/opt/castor/1.0.2/lib/castor/cli.rb:84:in `locked?': Found a lock. Exiting. (RuntimeError)
        from /opt/castor/1.0.2/lib/castor/core.rb:33:in `run'
```

Shouldn't raise, as it triggers a CRON mail.

Should check how old the lock is, and remove it if it's older than 15 mins.

**Comment by failshell** [comment]
Fixed by db66e08e99aff59f47.
